/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./src/components/AppShell.vue')['default']
    HomeView: typeof import('./src/components/HomeView.vue')['default']
    LoginView: typeof import('./src/components/LoginView.vue')['default']
    ManagedStreamPlayer: typeof import('./src/components/stream/ManagedStreamPlayer.vue')['default']
    NotificationsView: typeof import('./src/components/NotificationsView.vue')['default']
    SettingsView: typeof import('./src/components/SettingsView.vue')['default']
    StreamControls: typeof import('./src/components/stream/StreamControls.vue')['default']
    StreamPlayer: typeof import('./src/components/stream/StreamPlayer.vue')['default']
    StreamStatusBadge: typeof import('./src/components/stream/StreamStatusBadge.vue')['default']
    StreamTestView: typeof import('./src/components/StreamTestView.vue')['default']
  }
}
