/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./src/components/AppShell.vue')['default']
    EmergencyModal: typeof import('./src/components/EmergencyModal.vue')['default']
    GreetComponent: typeof import('./src/components/GreetComponent.vue')['default']
    HomeView: typeof import('./src/components/HomeView.vue')['default']
    LoginView: typeof import('./src/components/LoginView.vue')['default']
    NotificationsView: typeof import('./src/components/NotificationsView.vue')['default']
    SettingsView: typeof import('./src/components/SettingsView.vue')['default']
  }
}
